---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# CytOpT.R

<!-- badges: start -->
<!-- badges: end -->

The goal of CytOpT.R is to ...

## Installation

You can install the development version of CytOpT.R like so:
```{r example}
install.packages("CytOpT")
## basic example code
```

``` r
# FILL THIS IN! HOW CAN PEOPLE INSTALL YOUR DEV PACKAGE?
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
# Source Data
Stanford1A_values <- read.csv('tests/ressources/W2_1_values.csv')
Stanford1A_clust <- read.csv('tests/ressources/W2_1_clust.csv')[, 2]

# Target Data
Stanford3A_values <- read.csv('tests/ressources/W2_7_values.csv')
Stanford3A_clust <- read.csv('tests/ressources/W2_7_clust.csv')[, 2]

X_source <- convertArray(Stanford1A_values)
X_target <- convertArray(Stanford3A_values)



X_source <- X_source * (X_source > 0)
X_target <- X_target * (X_target > 0)

X_source <- Scale(X_source)
X_target <- Scale(X_target)

Lab_source <- convertArray(Stanford1A_clust)
Lab_target <- convertArray(Stanford3A_clust)

theta_true <- rep(0,10)
for (k in 1:10) theta_true[k] <- sum(Lab_target == k)/length(Lab_target)


# comparison two methods
CytOpt(X_source, X_target, Lab_source, theta_true=theta_true, method='comparison_opt')


```


